# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 731a5f78e024227bacd4600295d044d95a21569910be394a6c4c23218bf3fb1b9f1297f2c35364ab10e5dc31a3f877bedeb55e1c9b48ed67b71db6d76abb822b

test:
  secret_key_base: 1e6fc949d1e5583e67fb0b6a206f051476de8b369d8953e254b99d63e1ae1e57ed71a911e229a712aaa1386b216d6f6dc579ad3aceed7b194b66f47e30662478

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
